[build]
  publish = "."

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.html"
  [headers.values]
    Content-Type = "text/html"

[build.environment]
  NODE_VERSION = "18" 