import { NextResponse } from "next/server";

const products = [
  {
    id: "1",
    name: "Nguvu Cement 32.5 50Kg",
    price: 855,
    rating: 4.5,
    reviews: 60,
    inStock: true,
    image: "/api/placeholder/300/300",
    category: "Cement",
    description:
      "High-quality cement for general building and structural use. 80kgs net weight.",
    brand: "Bamburi",
    specifications: {
      weight: "50kg",
      type: "Portland Cement",
      strength: "32.5 MPa",
    },
  },
  {
    id: "2",
    name: "Nyumba Cement 32.5 50Kg",
    price: 750,
    rating: 4.5,
    reviews: 61,
    inStock: true,
    image: "/api/placeholder/300/300",
    category: "Cement",
    description:
      "Mombasa Cement NYUMBA brand. Save Energy for a better tomorrow.",
    brand: "Mombasa Cement",
    specifications: {
      weight: "50kg",
      type: "Portland Cement",
      strength: "32.5 MPa",
    },
  },
  {
    id: "3",
    name: "Simba Cement 32.5 50Kg",
    price: 735,
    rating: 4.5,
    reviews: 28,
    inStock: true,
    image: "/api/placeholder/300/300",
    category: "Cement",
    description: "NATIONAL CEMENT CO LTD. SIMBA CEMENT with lion logo.",
    brand: "National Cement",
    specifications: {
      weight: "50kg",
      type: "Portland Cement",
      strength: "32.5 MPa",
    },
  },
  {
    id: "4",
    name: "Maisha Aluzinc 3Mtrs",
    price: 818,
    rating: 4.5,
    reviews: 16,
    inStock: true,
    image: "/api/placeholder/300/300",
    category: "Mabati",
    description:
      "High-quality corrugated roofing sheets with aluminum-zinc coating.",
    brand: "Maisha",
    specifications: {
      length: "3 meters",
      material: "Aluzinc",
      thickness: "0.3mm",
    },
  },
  {
    id: "5",
    name: "Dumu T.Red Resincot CX 2.5 Mtrs",
    price: 1780,
    rating: 4.5,
    reviews: 90,
    inStock: true,
    image: "/api/placeholder/300/300",
    category: "Mabati",
    description:
      "Dumu corrugated roofing sheets in T.Red color with resin coating.",
    brand: "Dumu",
    specifications: {
      length: "2.5 meters",
      color: "T.Red",
      coating: "Resincot",
    },
  },
  {
    id: "6",
    name: "Dumu Maasai Red CX 3Mtrs",
    price: 1760,
    rating: 4.5,
    reviews: 72,
    inStock: true,
    image: "/api/placeholder/300/300",
    category: "Mabati",
    description: "Dumu corrugated roofing sheets in Maasai Red color.",
    brand: "Dumu",
    specifications: {
      length: "3 meters",
      color: "Maasai Red",
      type: "Corrugated",
    },
  },
  {
    id: "7",
    name: "DUMU SKYBLUE RESINCOT CX 2MTRS",
    price: 1440,
    rating: 4.5,
    reviews: 44,
    inStock: true,
    image: "/api/placeholder/300/300",
    category: "Mabati",
    description:
      "Dumu corrugated roofing sheets in Sky Blue color with resin coating.",
    brand: "Dumu",
    specifications: {
      length: "2 meters",
      color: "Sky Blue",
      coating: "Resincot",
    },
  },
  {
    id: "8",
    name: "KENTANK CYLINDRICAL 1000 LTRS WATER TANK",
    price: 7300,
    rating: 4.5,
    reviews: 34,
    inStock: true,
    image: "/api/placeholder/300/300",
    category: "Plumbing",
    description:
      "Large capacity water storage tank for commercial and residential use.",
    brand: "Kentank",
    specifications: {
      capacity: "1000 liters",
      shape: "Cylindrical",
      material: "Plastic",
    },
  },
  {
    id: "9",
    name: "BCL-4335C Bathroom Cabinet + Mirror Black",
    price: 7350,
    rating: 4.5,
    reviews: 52,
    inStock: true,
    image: "/api/placeholder/300/300",
    category: "Bathroom",
    description:
      "Modern bathroom cabinet with integrated mirror in black finish.",
    brand: "BCL",
    specifications: {
      color: "Black",
      material: "Wood",
      includes: "Mirror",
    },
  },
  {
    id: "10",
    name: "Chandelier-18005/6+3",
    price: 53000,
    rating: 4.5,
    reviews: 93,
    inStock: true,
    image: "/api/placeholder/300/300",
    category: "Lighting",
    description: "Elegant crystal chandelier with multiple light sources.",
    brand: "Chandelier",
    specifications: {
      bulbs: "6+3",
      style: "Crystal",
      voltage: "220V",
    },
  },
];

export async function GET() {
  return NextResponse.json(products);
}
